permissions:
  contents: read
  pull-requests: write

runs:
  using: composite
  steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.CREATE_APP_TOKEN_APP_ID }}
        private-key: ${{ secrets.CREATE_APP_TOKEN_PRIVATE_KEY }}
    - name: run conventional commit
      uses: hmarr/auto-approve-action@v4
      with:
        github-token: ${{ steps.app-token.outputs.token }}
