outputs:
  url:
    description: URL of deployed preview
    value: ${{ steps.deploy.outputs.url }}

inputs:
  VERCEL_TOKEN:
    description: vercel token
    required: true

runs:
  using: composite
  steps:
    - name: Initialize environment
      uses: ./.github/workflows/actions/init
    - name: Install Vercel CLI
      run: pnpm install --global vercel@latest
      shell: bash
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ inputs.VERCEL_TOKEN }}
      shell: bash
    - name: Build Project Artifacts
      run: vercel build --token=${{ inputs.VERCEL_TOKEN }}
      shell: bash
    - name: Deploy Project Artifacts to Vercel
      id: deploy
      run: echo "url=$(vercel deploy --prebuilt --token=${{ inputs.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT
      shell: bash
