name: Auto approve

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.AUTO_APPROVE_APP_ID }}
          private-key: ${{ secrets.AUTO_APPROVE_APP_PRIVATE_KEY }}
      - uses: hmarr/auto-approve-action@v4
        name: Auto approve PR
        with:
          github-token: ${{ steps.app-token.outputs.token }}
