name: Check PR name and body
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  conventional-commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app_id: ${{ secrets.CREATE_APP_TOKEN_APP_ID }}
          private_key: ${{ secrets.CREATE_APP_TOKEN_PRIVATE_KEY }}
      - name: run conventional commit
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ steps.app-token.outputs.token }}

