name: conventional-commit
on:
  pull_request:
    branches: [ main ]
    types: [opened, edited, synchronize]

jobs:
    conventional-commit:
      runs-on: ubuntu-latest
      steps:
        - name: validate pr title and body
          uses: agenthunt/conventional-commit-checker-action@v2.0.0
