name: conventional-commit
on:
  pull_request:

jobs:
    conventional-commit:
      steps:
        - name: Conventional Commit Checker
          uses: agenthunt/conventional-commit-checker-action@v2.0.0
      runs-on: ubuntu-latest