name: Deploy staging

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy preview
        id: deploy-preview
        uses: ./.github/workflows/actions/deploy-preview
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Assign staging domain to deployment
        run: vercel alias ${{ steps.deploy-preview.outputs.url }} staging-voice0726.vercel.app --scope=voice726 --token=${{ secrets.VERCEL_TOKEN }}
