name: Deploy non-production

on:
  push:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  check-changed-files:
    name: "Check changed files"
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.output-to-env.outputs.skip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Check changed files"
        id: check-changed-files
        uses: ./.github/workflows/actions/get-changed-files
      - name: Output result to env
        id: output-to-env
        run: |
          echo any_changed=${{ steps.check-changed-files.outputs.any_changed }}
          echo changed_files=${{ steps.check-changed-files.outputs.all_changed_files }}
          echo renovate=${{ startsWith('renovate', github.ref_name) }}
          echo "skip=${{ steps.check-changed-files.outputs.any_changed == 'false' || startsWith('renovate', github.ref_name) }}" >> "$GITHUB_OUTPUT"
  deploy:
    needs: check-changed-files
    runs-on: ubuntu-latest
    if: ${{ needs.check-changed-files.outputs.skip == 'false' && github.ref_name != 'main' && !startsWith(github.ref_name, 'release-please' ) }}
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy preview
        id: deploy-preview
        uses: ./.github/workflows/actions/deploy
        with:
          VERCEL_ORG_ID: ${{ env.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ env.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TARGET_ENVIRONMENT: preview

  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    if: ${{ github.ref_name == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy staging
        id: deploy-staging
        uses: ./.github/workflows/actions/deploy
        with:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TARGET_ENVIRONMENT: staging