name: Deploy non-production

on:
  push:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changed-files:
    name: "Check changed files"
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.output-to-env.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Check changed files"
        id: check-changed-files
        uses: ./.github/workflows/actions/get-changed-files
      - name: Output result to env
        id: output-to-env
        run: |
          echo any_changed=${{ steps.check-changed-files.outputs.any_changed }} >> "$GITHUB_OUTPUT"

  deploy-preview:
    name: Deploy preview
    needs: check-changed-files
    runs-on: ubuntu-latest
    if: ${{ needs.check-changed-files.outputs.any_changed == 'true' && github.ref_name != 'main' }}
    environment:
      name: url
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy preview
        id: deploy-preview
        uses: ./.github/workflows/actions/deploy
        with:
          VERCEL_ORG_ID: ${{ env.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ env.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TARGET_ENVIRONMENT: preview

  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    if: ${{ github.ref_name == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy staging
        id: deploy-staging
        uses: ./.github/workflows/actions/deploy
        with:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TARGET_ENVIRONMENT: staging