name: Check PR

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: write

defaults:
  run:
    shell: bash

jobs:
  check-changed-files:
    name: "Check changed files"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Check changed files"
        id: check-changed-files
        uses: ./.github/workflows/actions/get-changed-files
      - name: Output result to env
        run: |
          echo any_changed=${{ steps.check-changed-files.outputs.any_changed }}
          echo changed_files=${{ steps.check-changed-files.outputs.all_changed_files }}
          echo renovate=${{ startsWith('renovate', github.ref_name) }}
          echo "skip=${{ steps.check-changed-files.outputs.any_changed == 'false' || startsWith('renovate', github.ref_name) }}" >> "$GITHUB_ENV"
  tsc-lint:
    name: "Run typechecking and linting"
    needs: check-changed-files
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo ${{toJSON(env)}}
      - name: check skippable
        if: env.skip == 'true'
        run: exit 0
      - name: checkout
        uses: actions/checkout@v4
      - name: type check and lint
        uses: ./.github/workflows/actions/typecheck-and-lint
  test:
    name: "Run test"
    needs: tsc-lint
    runs-on: ubuntu-latest
    steps:
      - name: check skippable
        if: env.skip == 'true'
        run: exit 0
      - name: checkout
        uses: actions/checkout@v4
      - name: Run test
        uses: ./.github/workflows/actions/test
  code-analysis:
    name: "Run code analysis by qodana"
    needs: tsc-lint
    runs-on: ubuntu-latest
    steps:
      - name: check skippable
        if: env.skip == 'true'
        run: exit 0
      - name: checkout
        uses: actions/checkout@v4
      - name: Get changed files
        uses: ./.github/workflows/actions/get-changed-files
        id: check-changed-files
      - name: Run qodana code scanning
        uses: ./.github/workflows/actions/qodana
        if: ${{ steps.check-changed-files.outputs.any_changed }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1290658496 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
  output:
    runs-on: ubuntu-latest
    name: Show results of checking Pull Request
    needs: [ test, code-analysis ]
    steps:
      - name: Skipped
        if: ${{ always() && env.skip }}
        run: |
          echo "Skipped checking PR"
      - name: Succeeded
        if: ${{ always() && !env.skip && !contains(join(needs.*.result, ','), 'failure') }}
        run: |
          echo "Finished checking PR successfully"
      - name: Failed
        if: ${{ always() && !env.skip && contains(join(needs.*.result, ','), 'failure') }}
        run: |
          echo "Some checks are not passed"
          exit 1

