name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get changed files
        uses: tj-actions/changed-files@v45.0.7
        id: changed-files
        with:
          files: |
            **/*.{js,jsx,ts,tsx,cjs,mjs,cts,mts}
          files_separator: "\n"
      - name: Output changed files
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}
  qodana:
    needs: [ get-changed-files ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Get changed files
        uses: ./.github/workflows/actions/get-changed-files
        id: check-changed-files
      - name: Run qodana code scanning
        uses: ./.github/workflows/actions/qodana
        if: ${{ steps.check-changed-files.outputs.any-changed }}

