name: renovate
on:
  push:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  typechekck-and-linting:
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'renovate')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialize
        uses: ./.github/workflows/actions/init
      - name: Typecheck and lint
        uses: ./.github/workflows/actions/typecheck-and-lint