name: vitest]

on:
  push:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Run test codes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check changed files
        uses: ./.github/workflows/actions/get-changed-files
        id: check-changed-files
      - name: Initialize
        uses: ./.github/workflows/actions/init
        if: ${{ steps.check-changed-files.outputs.any-changed }}
      - name: Run Vitest
        uses: ./.github/workflows/actions/test
        if: ${{ steps.check-changed-files.outputs.any-changed }}
