name: vitest

on:
  push:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get changed files
        uses: tj-actions/changed-files@v45.0.7
        id: changed-files
        with:
          files: |
            src/**/*.{js,jsx,ts,tsx}
          files_separator: "\n"
      - name: Output changed files
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}
  test:
    needs: [ get-changed-files ]
    name: Run test codes
    runs-on: ubuntu-latest
    if: needs.get-changed-files.outputs.any_changed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check changed files
        uses: ./.github/workflows/actions/get-changed-files
        id: check-changed-files
      - name: Initialize
        uses: ./.github/workflows/actions/init
        if: ${{ steps.check-changed-files.outputs.any-changed }}
      - name: Run Vitest
        uses: ./.github/workflows/actions/test
        if: ${{ steps.check-changed-files.outputs.any-changed }}
