name: typecheck-and-eslint.yml
on:
  push:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  typechekck-and-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/workflows/_prepare.yml
      - name: Type check
        run: pnpm run types:check
      - name: Eslint
        run: pnpm run lint:check