runs:
  using: composite
  steps:
    - name: Initialize
      uses: ./.github/workflows/actions/init
    - name: Type check
      run: pnpm run types:check
      shell: bash
    - name: Eslint
      run: pnpm run lint:check
      shell: bash
